os: linux
language: android
jdk: oraclejdk8
android:
  components:
  - tools
cache:
  directories:
  - "~/android"
install:
- sudo apt-get update
- sudo apt-get install -y ninja-build bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk
- mkdir -p ~/bin
- mkdir -p ~/android
- curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
- chmod a+x ~/bin/repo
- export PATH="$HOME/bin:$PATH"
- export USE_CCACHE=1
- ccache -M 100G
- export CCACHE_COMPRESS=1
- export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"
- export WITH_SU=true
before_script:
- cd ~/android
- travis_retry yes | repo init -u https://github.com/LineageOS/android.git -b cm-14.1
- rm -f ~/nohup.out
- nohup repo sync -j 16 -c &
- while true; do  sleep 9m; if [ -z `pgrep python` ]; then break; else ps -ef | grep python --color; fi; done
- ps -ef
script:
- travis_wait 120 source ~/android/build/envsetup.sh
- croot
- breakfast cancro || ( python $TRAVIS_BUILD_DIR/repo.modify.py ~/android/.repo/local_manifests/roomservice.xml && breakfast canro )
- nohup brunch cancro &
- travis_wait 360 while true; do  sleep 9m; if [ -z `pgrep make` ]; then break; else echo "It's Building now"; fi; done
after_failure:
- echo "==========Build Failed============"
- tail --lines=500 ~/nohup.out
